### ISSUE TITLE
[Bug] Error: "Template not found" during install

### ISSUE THREAD

**Issue by nateemerson** [danstepanov/create-expo-stack#15]
I tried running the CLI and got an error (using both `pnpx` and `npx` @latest).

## Reproduction Steps:
1. Run `npx create-expo-stack@latest`
2. Use all default options for the CLI

**Expected outcome:** CLI creates a new directory and finishes without errors
**Actual outcome:** "Oops, something went wrong while creating your project 😢
Error: template not found" (see full output below)

System details:
NPM: 9.6.6
PNPM: 8.3.1
OS: M2 MacBook Air (2022)
Terminal: Kitty 0.26.5

My terminal log (including selections from CLI):

```
pnpx create-expo-stack@latest
.../share/pnpm/store/v3/tmp/dlx-7568     | +152 +++++++++++++++
.../share/pnpm/store/v3/tmp/dlx-7568     | Progress: resolved 152, reused 117, downloaded 35, added 152, done
✔ What do you want to name your project? (my-expo-app) · touch-grass
✔ Would you like to use TypeScript with this project? (Y/n) · true
Good call, now using TypeScript! 🚀
✔ What would you like to use for Navigation? · Expo Router
✔ What type of navigation would you like to use? · Stack
Great, we'll use Expo Router!
✔ Would you like to use NativeWind (Tailwind for RN) with this project? (Y/n) · true
You'll be styling with ease using Tailwind.

Initializing your project...

Oops, something went wrong while creating your project 😢
Error: template not found /Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/create-expo-stack@2.0.1/node_modules/create-expo-stack/build/build/templates/base/assets/adaptive-icon.png
    at /Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/gluegun@5.1.4/node_modules/gluegun/build/toolbox/template-tools.js:82:27
    at step (/Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/gluegun@5.1.4/node_modules/gluegun/build/toolbox/template-tools.js:44:23)
    at Object.next (/Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/gluegun@5.1.4/node_modules/gluegun/build/toolbox/template-tools.js:25:53)
    at /Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/gluegun@5.1.4/node_modules/gluegun/build/toolbox/template-tools.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/gluegun@5.1.4/node_modules/gluegun/build/toolbox/template-tools.js:15:12)
    at generate (/Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/gluegun@5.1.4/node_modules/gluegun/build/toolbox/template-tools.js:64:16)
    at /Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/create-expo-stack@2.0.1/node_modules/create-expo-stack/build/commands/create-expo-stack.js:274:35
    at Array.reduce (<anonymous>)
    at /Users/nate/.local/share/pnpm/store/v3/tmp/dlx-7568/node_modules/.pnpm/create-expo-stack@2.0.1/node_modules/create-expo-stack/build/commands/create-expo-stack.js:255:44

If this was unexpected, please open an issue: https://github.com/danstepanov/create-expo-stack#reporting-bugs--feedback
```

**Comment by nateemerson** [comment]
Update: Tried again today with default and pnpm flags, got the same result. Now it's using `create-expo-stack@2.0.6`

```
❯ npx create-expo-stack@latest --default --pnpm
Need to install the following packages:
  create-expo-stack@2.0.6
Ok to proceed? (y) y
✔ What do you want to name your project? (my-expo-app) · expostacktestflags
✔ Would you like to use TypeScript with this project? (Y/n) · true
Good call, now using TypeScript! 🚀
✔ What would you like to use for Navigation? · Expo Router
✔ What type of navigation would you like to use? · Stack
Great, we'll use Expo Router!
✔ Would you like to use NativeWind (Tailwind for RN) with this project? (Y/n) · true
You'll be styling with ease using Tailwind.

Initializing your project...

Oops, something went wrong while creating your project 😢
Error: template not found /Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/create-expo-stack/build/build/templates/base/assets/adaptive-icon.png
    at /Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/gluegun/build/toolbox/template-tools.js:82:27
    at step (/Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/gluegun/build/toolbox/template-tools.js:44:23)
    at Object.next (/Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/gluegun/build/toolbox/template-tools.js:25:53)
    at /Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/gluegun/build/toolbox/template-tools.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/gluegun/build/toolbox/template-tools.js:15:12)
    at generate (/Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/gluegun/build/toolbox/template-tools.js:64:16)
    at /Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/create-expo-stack/build/commands/create-expo-stack.js:327:35
    at Array.reduce (<anonymous>)
    at /Users/nate/.npm/_npx/7db5f7bb998dd32f/node_modules/create-expo-stack/build/commands/create-expo-stack.js:308:44

If this was unexpected, please open an issue: https://github.com/danstepanov/create-expo-stack#reporting-bugs--feedback
```

After this run, I tried a simple `npx create-expo-stack@latest` with no flags and got the same error. I then cleared my npx cache and tried again, verifying that this command is pulling 2.0.6 and I get the same error no matter the options I select. First time I tried with my preferred selections (TS, Expo navigation, stack, nativewind), second time I tried with minimal selections (no TS, no navigation, no nativewind) and I get the same error in both cases.

**Comment by danstepanov** [comment]
I'm able to recreate the issue. I'm thinking it has to do with the double `build` folder nonsense, see `build/build` in the error message. But not sure when that was introduced as an issue. Oddly, this all works fine when running create-expo-stack locally (not via npx).

![Screenshot 2023-10-01 at 10 17 27 PM](https://github.com/danstepanov/create-expo-stack/assets/5482800/b461337c-d8c6-40b9-8c45-b4add247401a)

**Comment by danstepanov** [comment]
The error seems to have occurred when moving from `v0.1.4` to `v2.0.0`

**Comment by danstepanov** [comment]
Alright, so it seems that basically all of the template files are not included in the build that goes to the npm registry, for whatever reason.

![Screenshot 2023-10-01 at 10 56 10 PM](https://github.com/danstepanov/create-expo-stack/assets/5482800/5ffaca94-2592-42e3-b20e-09a1c9c52e3a)
