### ISSUE TITLE
EAS Update with Error

### ISSUE THREAD

**Issue by prawee** [danstepanov/create-expo-stack#183]
## Expected Behavior

i'm create with CLI 
`npx create-expo-stack es-stack --expo-router --tamagui --yarn
cd es-stack`

## Current Behavior

i want to test push to Expo
`eas update`

## Detailed Description

`
Generated by create-expo-stack 2.0.0.
[expo-cli] /Users/prawee/code/expo/es-stack/node_modules/wrap-ansi/index.js:2
[expo-cli] const stringWidth = require('string-width');
[expo-cli]                     ^
[expo-cli]
[expo-cli] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/prawee/code/expo/es-stack/node_modules/string-width/index.js from /Users/prawee/code/expo/es-stack/node_modules/wrap-ansi/index.js not supported.
[expo-cli] Instead change the require of /Users/prawee/code/expo/es-stack/node_modules/string-width/index.js in /Users/prawee/code/expo/es-stack/node_modules/wrap-ansi/index.js to a dynamic import() which is available in all CommonJS modules.
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/wrap-ansi/index.js:2:21)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/start/doctor/dependencies/ensureDependenciesAsync.js:9:40)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/start/doctor/web/WebSupportProjectPrerequisite.js:12:32)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:20:38)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js:23:31)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:11:25)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/export/createBundles.js:9:24)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/export/exportApp.js:14:22)
[expo-cli]     at Object.<anonymous> (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/export/exportAsync.js:10:18)
[expo-cli]     at /Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/export/index.js:83:40
[expo-cli]     at async expoExport (/Users/prawee/code/expo/es-stack/node_modules/@expo/cli/build/src/export/index.js:82:30) {
[expo-cli]   code: 'ERR_REQUIRE_ESM'
[expo-cli] }
[expo-cli]
[expo-cli] Node.js v18.19.0
✖ Export failed
`

**Comment by danstepanov** [comment]
```
test npx create-expo-stack es-stack --expo-router --tamagui --yarn
                          _
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\


Your project configuration:
{
  projectName: 'es-stack',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'stack' }
    },
    { name: 'tamagui', type: 'styling' }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'yarn'
  }
}

To recreate this project, run:
  npx create-expo-stack es-stack --expo-router --tamagui --yarn

Initializing your project...

Copying base assets...

Installing dependencies using yarn...

warning ../../package.json: No license field
warning expo-linking > expo-constants > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning expo > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning expo > expo-file-system > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning expo > babel-preset-expo > @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
warning expo > babel-preset-expo > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
warning expo > @expo/cli > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
warning react-native > @react-native/codegen > jscodeshift > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
warning react-native > @react-native/codegen > jscodeshift > @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
warning react-native > @react-native/codegen > jscodeshift > @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer > babel-preset-fbjs > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer > babel-preset-fbjs > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning " > expo-router@2.0.14" has unmet peer dependency "expo-constants@*".
warning " > expo-router@2.0.14" has unmet peer dependency "metro@~0.76.7".
warning "expo-router > expo-splash-screen > @expo/prebuild-config@6.2.6" has unmet peer dependency "expo-modules-autolinking@>=0.8.1".
warning "react-native > @react-native/codegen@0.72.8" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "react-native > @react-native/codegen > jscodeshift@0.14.0" has unmet peer dependency "@babel/preset-env@^7.1.6".

Cleaning up your project...

yarn run v1.22.19
warning ../../package.json: No license field
$ eslint "**/*.{js,jsx,ts,tsx}" --fix && prettier "**/*.{js,jsx,ts,tsx,json}" --write
app.json 20ms
app/_layout.tsx 87ms (unchanged)
app/[...unmatched].tsx 3ms (unchanged)
app/+html.tsx 5ms (unchanged)
app/details.tsx 7ms (unchanged)
app/index.tsx 2ms (unchanged)
babel.config.js 4ms (unchanged)
index.ts 0ms (unchanged)
metro.config.js 2ms (unchanged)
package.json 1ms
tamagui.config.ts 9ms (unchanged)
tsconfig.json 1ms
✨  Done in 1.97s.

Initializing git...

Success! 🎉 Now, just run the following to get started:

cd es-stack
yarn ios

If you frequently use create expo stack, please consider sponsoring the project ❤️
https://github.com/sponsors/danstepanov
➜  test cd es-stack
➜  es-stack git:(main) eas update
zsh: command not found: eas
```

I don't understand this issue

**Comment by danstepanov** [comment]
Closing this for now, unless more info comes in
