### ISSUE TITLE
Erroe while using npx create-expo-stack@latest

### ISSUE THREAD

**Issue by LollyTim** [danstepanov/create-expo-stack#334]
\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\gluegun\build\index.js:15
    throw up;
    ^

SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
    at new SystemError (node:internal/errors:238:5)
    at new NodeError (node:internal/errors:349:7)
    at new WriteStream (node:tty:94:11)
    at n.prompt (C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\@clack\core\dist\index.cjs:9:890)
    at text (C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\@clack\prompts\dist\index.cjs:9:7)
    at C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\create-expo-stack\build\commands\create-expo-stack.js:67:55
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\create-expo-stack\build\commands\create-expo-stack.js:5:58) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -4083,
    code: 'EBADF',
    message: 'bad file descriptor',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

**Comment by LollyTim** [comment]
\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\gluegun\build\index.js:15
    throw up;
    ^

SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
    at new SystemError (node:internal/errors:238:5)
    at new NodeError (node:internal/errors:349:7)
    at new WriteStream (node:tty:94:11)
    at n.prompt (C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\@clack\core\dist\index.cjs:9:890)
    at text (C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\@clack\prompts\dist\index.cjs:9:7)
    at C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\create-expo-stack\build\commands\create-expo-stack.js:67:55
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\olola\AppData\Local\npm-cache\_npx\7db5f7bb998dd32f\node_modules\create-expo-stack\build\commands\create-expo-stack.js:5:58) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -4083,
    code: 'EBADF',
    message: 'bad file descriptor',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

**Comment by LollyTim** [comment]
I got this error while using this npx create-expo-stack
